algoritmo "quest48"
// Função : Faça um programa que leia 7 números inteiros e no final mostre o somatório
//entre eles.
// Autor : Jefferson
// Data : 24/01/2021
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara
var
cont, Num, soma: inteiro
inicio
cont <- 1
enquanto (cont <= 7) faca
   escreva ("Digite o ", cont, "º número: ")
   leia (Num)
   soma <- soma + Num
   cont <- cont + 1
Fimenquanto
escreva ("A soma entre os números é ", soma)
fimalgoritmo
