algoritmo "quest06"
// Função :  Leitura de um númeo inteiro mostrando antecessor e sucessor.
// Autor :   Jefferson
// Data : 05/01/2021
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara
var
     N, Na, Ns: inteiro
inicio
      escreva ("Digite um número: ")
      leia (N)
      Na <- N - 1
      Ns <- N + 1
      escreval ("O antecessor de ", N, " é ", Na)
      escreva ("O sucessor de ", N, " é ", Ns)

fimalgoritmo
