algoritmo "quest04"
// Função : Algoritimo para ler dois números inteiros e mostrar o somatório entre eles.
// Autor : Jefferson
// Data : 05/01/2021
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara
var
    v1, v2, Soma: inteiro

inicio
escreva ("Digite um valor: ")
leia (v1)
escreva ("digite outro valor: ")
leia (v2)
Soma <- v1 + v2
escreva ("A soma entre ", v1, " e", v2, " é igual a ", Soma, ".")
fimalgoritmo
