algoritmo "quest61"
// Função : Crie um programa que mostre na tela a seguinte contagem, usando a estrutura
//“faça enquanto”
//0 3 6 9 12 15 18 21 24 27 30 Acabou!
// Autor : Jefferson
// Data : 01/02/2021
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara
var
Cont: inteiro
inicio
Cont <- 0
repita
      escreva (Cont)
      Cont <- Cont + 3
ate (Cont > 30)
escreva (" Acabou!")
fimalgoritmo
