algoritmo "quest67"
// Função : Faça um programa usando a estrutura “para” que leia um número inteiro
//positivo e mostre na tela uma contagem de 0 até o valor digitado:
//Ex: Digite um valor: 9
//Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!
// Autor :  Jefferson
// Data : 03/02/2021
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara
var
N, C: inteiro
inicio
escreva ("Digite um número: ")
leia (N)
para C <- 0 ate N faca
   escreva (C)
Fimpara
escreval (" FIM!")
fimalgoritmo
